services:
    db:
      image: postgres:16
      container_name: tailnet_db
      restart: unless-stopped
      environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
      ports:
        - "5432:5432"
      volumes:
        - tailnet_volume:/var/lib/postgresql/data
      healthcheck:
        test: ["CMD-SHELL","pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
        interval: 10s
        timeout: 5s
        retries: 5
        start_period: 10s
      deploy:
        resources:
          limits:
            cpus: "0.5"
            memory: "1000M"
          reservations:
            cpus: "0.25"
            memory: "500M"

volumes:
  tailnet_volume:
    external: true